version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - .env.dev

  web:
    build:
      context: .  # Use the current directory as the build context
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app  # Mount the current directory into the container's /app directory
